[all_follow]
nixpkgs = "nixpkgs"

[inputs.nixpkgs]
url = "https://channels.nixos.org/nixos-unstable/nixexprs.tar.xz"

[inputs.treefmt-nix]
url = "github:numtide/treefmt-nix"

[inputs.disko]
url = "github:nix-community/disko"

[inputs.impermanence]
url = "github:nix-community/impermanence"

[inputs.nix-wrapper-modules]
url = "github:birdeehub/nix-wrapper-modules"

[inputs.monique]
url = "github:torvaldz/monique"
follows = { flake-utils = "flake-utils" }

[inputs.flake-utils]
url = "github:numtide/flake-utils"

[inputs.nixcord]
url = "github:flameflag/nixcord"

[inputs.nix-index-database]
url = "github:nix-community/nix-index-database"

[inputs.sops-nix]
url = "github:Mic92/sops-nix"

[inputs.noctalia]
url = "github:noctalia-dev/noctalia/cachix"

[inputs.tack]
url = "github:manic-systems/tack"
